#!/bin/bash
set -o errexit
set -o xtrace

# there should be a docker process
docker ps | grep -q caddy-gen
# it should be available and return 404
curl 127.0.0.1:80
# test image size (see wemake-services/docker-image-size-limit)
disl caddy-gen:latest 90MB
# test feature CADDY_TEMPLATE
printf "http://test-template.localhost {\n  respond \"template\"\n}\n" > template.tmpl
docker cp template.tmpl caddy-gen:/tmp/template.tmpl
docker exec caddy-gen sh -c "export CADDY_TEMPLATE=/tmp/template.tmpl && sh /code/docker-entrypoint.sh"
test "$(curl 0.0.0.0:80 -s -H 'Host: test-template.localhost')" == "template"
# test feature CADDY_SNIPPET
printf "http://test-snippet.localhost {\n  respond \"snippet\"\n}\n" > snippet.tmpl
docker cp snippet.tmpl caddy-gen:/tmp/snippet.tmpl
docker exec caddy-gen sh -c "export CADDY_TEMPLATE=/tmp/template.tmpl CADDY_SNIPPET=/tmp/snippet.tmpl && sh /code/docker-entrypoint.sh"
test "$(curl 0.0.0.0:80 -s -H 'Host: test-template.localhost')" == "template"
test "$(curl 0.0.0.0:80 -s -H 'Host: test-snippet.localhost')" == "snippet"
