#!/bin/sh

set -o errexit
set -o xtrace

# Adds dependencies:
pip install docker-image-size-limit

# Building image itself:
docker build -t caddy-gen:latest .
docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro --name caddy-gen caddy-gen
